### ISSUE TITLE
question 1

### ISSUE THREAD

**Issue by starrkone** [starrkone/test-1#5]
what about this code :
```html
<!DOCTYPE html>
<html>
<head>
  <title>hello</title>
</head>
<body>
  <a href="index.html">HOME</a>
</body>
</html>
```

**Comment by starrk66** [comment]
it's ok..no problem.

**Comment by starrkone** [comment]
> what about this code :

@starrk66 what would be like if you code this.

**Comment by starrk66** [comment]
@starrkone i think No.3 row is not good .

**Comment by starrkone** [comment]
OK, everything is ok .
issue finished.
